In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    'label':      ['spam', 'ham', 'spam', 'ham', 'spam', 'ham'],
    'word_count': [5, 5, 6, 4, 5, 5],
    'has_link':   [1, 0, 1, 0, 1, 0]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  label  word_count  has_link
0  spam           5         1
1   ham           5         0
2  spam           6         1
3   ham           4         0
4  spam           5         1
5   ham           5         0

In [13]:
# Group by label, calculate mean
# df.groupby('label')['word_count'].mean()

# sum
# df.groupby('label')['word_count'].sum()

# count — how many emails in each group
# df.groupby('label')['word_count'].count()

# max and min
# df.groupby('label')['word_count'].max()
# df.groupby('label')['word_count'].min()

# Multiple columns at once
df.groupby('label')[['word_count', 'has_link']].mean()

       word_count  has_link
label
ham      4.666667       0.0
spam     5.333333       1.0

### With groupby() alone: run separate lines for each calculation:
##### pythondf.groupby('label')['word_count'].mean()   # line 1
##### df.groupby('label')['word_count'].max()    # line 2
##### df.groupby('label')['word_count'].min()    # line 3
##### df.groupby('label')['word_count'].count()  # line 4
##### That's 4 separate outputs — messy and slow.
##### agg() does all of this in one line with one clean table.

In [14]:
# Multiple calculations at once
df.groupby('label')['word_count'].agg(['mean', 'max', 'min', 'count'])

           mean  max  min  count
label
ham    4.666667    5    4      3
spam   5.333333    6    5      3

In [15]:
# Different calculations for different columns

df.groupby('label').agg({
    'word_count': ['mean', 'max', 'min'],
    'has_link':   ['sum', 'mean']
})

      word_count         has_link
            mean max min      sum mean
label
ham     4.666667   5   4        0  0.0
spam    5.333333   6   5        3  1.0

#### Why use lambda in ML?
##### Sometimes built-in functions like mean, max, min aren't enough. You need a custom calculation — like range, or percentage, or something specific to your data.
##### Lambda lets you do that without writing a separate function.

#### Example:

#### df.groupby('label')['word_count'].agg(lambda x: x.max() - x.min())

#### df.groupby('label')        → split into spam group and ham group
#### ['word_count']             → look at word_count column only
#### .agg(lambda x: ...)        → apply this custom calculation to each group
#### lambda x: x.max()-x.min()  → calculate max minus min (range)

In [17]:
df.groupby('label')['word_count'].agg(lambda x: x.max() - x.min())

label
ham     1
spam    1
Name: word_count, dtype: int64

In [18]:
# Percentage of emails with links per group
df.groupby('label')['has_link'].agg(lambda x: x.sum() / len(x) * 100)

label
ham       0.0
spam    100.0
Name: has_link, dtype: float64